# backend/engines/causal_chain_engine.py
"""
Veridian Causal Chain Engine — The 7-Step Protocol

This is the core intelligence of Veridian. When an anomalous signal
is detected, this engine constructs a causal chain explaining WHY
it happened, WHAT will happen next, and HOW confident we should be.

The 7 Steps:
    1. ANOMALY CONFIRMATION   — Is this signal statistically anomalous?
    2. EVIDENCE RETRIEVAL     — What related signals exist in memory?
    3. HYPOTHESIS GENERATION  — What could explain this cluster? (Gemini)
    4. HYPOTHESIS TESTING     — Does evidence support or contradict? (Elastic + Gemini)
    5. WINNER SELECTION       — Which hypothesis survives testing?
    6. ACTIVE DISCONFIRMATION — Can we BREAK the winning hypothesis?
    7. CONFIDENCE CALIBRATION — What confidence does the evidence warrant?

Critical Design Principle:
    Gemini NEVER invents facts. It reasons ONLY over what Elastic retrieved.
    Every claim must cite signal IDs. Every hypothesis must be testable.
"""

from __future__ import annotations

import os
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
from enum import Enum
from typing import Any

import structlog

from backend.mcp.client import VeridianMCPClient
from backend.mcp.schemas import (
    FindRelatedSignalsOutput,
    AnomalyResult,
    EntityState,
    FindHistoricalPatternOutput,
    PredictionType,
    SignalResult,
)

logger = structlog.get_logger(__name__)


# ============================================================
# DATA MODELS
# ============================================================

class ChainStatus(str, Enum):
    BUILDING = "building"
    ACTIVE = "active"
    VALIDATED = "validated"
    REJECTED = "rejected"
    EXPIRED = "expired"


class HypothesisVerdict(str, Enum):
    SURVIVED = "survived"
    ELIMINATED = "eliminated"


class DisconfirmationVerdict(str, Enum):
    STANDS = "stands"
    MODIFIED = "modified"
    REJECTED = "rejected"


@dataclass
class AuditStep:
    """Single step in the reasoning audit trail."""
    step_number: int
    step_name: str
    tool_used: str
    input_summary: str
    output_summary: str
    reasoning: str
    timestamp: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())

    def to_dict(self) -> dict:
        return {
            "step_number": self.step_number,
            "step_name": self.step_name,
            "tool_used": self.tool_used,
            "input_summary": self.input_summary,
            "output_summary": self.output_summary,
            "reasoning": self.reasoning,
            "timestamp": self.timestamp,
        }


@dataclass
class Hypothesis:
    """A single hypothesis generated by Gemini."""
    hypothesis_id: str
    center_entity: str
    proposed_cause: str
    proposed_effect: str
    causal_mechanism: str
    supporting_signal_ids: list[str]
    disconfirmation_test: str
    initial_confidence: float
    timeline_estimate_days: int | None = None

    def to_dict(self) -> dict:
        return {
            "hypothesis_id": self.hypothesis_id,
            "center_entity": self.center_entity,
            "proposed_cause": self.proposed_cause,
            "proposed_effect": self.proposed_effect,
            "causal_mechanism": self.causal_mechanism,
            "supporting_signal_ids": self.supporting_signal_ids,
            "disconfirmation_test": self.disconfirmation_test,
            "initial_confidence": self.initial_confidence,
            "timeline_estimate_days": self.timeline_estimate_days,
        }


@dataclass
class HypothesisTestResult:
    """Result of testing a hypothesis against evidence."""
    hypothesis: Hypothesis
    evidence_strength: float
    consistency: float
    contradiction_severity: float
    causal_specificity: float
    alternative_explanation_risk: float
    overall_score: float
    supporting_signals_found: int
    contradicting_signals_found: int
    verdict: HypothesisVerdict
    decisive_reason: str

    def to_dict(self) -> dict:
        return {
            "hypothesis_id": self.hypothesis.hypothesis_id,
            "evidence_strength": self.evidence_strength,
            "consistency": self.consistency,
            "contradiction_severity": self.contradiction_severity,
            "causal_specificity": self.causal_specificity,
            "alternative_explanation_risk": self.alternative_explanation_risk,
            "overall_score": self.overall_score,
            "supporting_signals_found": self.supporting_signals_found,
            "contradicting_signals_found": self.contradicting_signals_found,
            "verdict": self.verdict.value,
            "decisive_reason": self.decisive_reason,
        }


@dataclass
class DisconfirmationResult:
    """Result of actively trying to break the winning hypothesis."""
    verdict: DisconfirmationVerdict
    challenge_signals_found: int
    reverse_causation_risk: str
    confounding_variable_risk: str
    absent_evidence_assessment: str
    scope_adjustment: str
    modified_hypothesis: str | None = None
    killer_evidence: str | None = None
    confidence_adjustment: float = 0.0

    def to_dict(self) -> dict:
        return {
            "verdict": self.verdict.value,
            "challenge_signals_found": self.challenge_signals_found,
            "reverse_causation_risk": self.reverse_causation_risk,
            "confounding_variable_risk": self.confounding_variable_risk,
            "absent_evidence_assessment": self.absent_evidence_assessment,
            "scope_adjustment": self.scope_adjustment,
            "modified_hypothesis": self.modified_hypothesis,
            "killer_evidence": self.killer_evidence,
            "confidence_adjustment": self.confidence_adjustment,
        }


@dataclass
class CausalChain:
    """Complete causal chain — the output of the 7-step protocol."""
    chain_id: str
    trigger_signal_id: str
    trigger_content: str
    center_entity: str
    proposed_cause: str
    proposed_effect: str
    predicted_timeline_days: int | None
    confidence: float
    supporting_signal_ids: list[str]
    contradicting_signal_ids: list[str]
    key_assumptions: list[str]
    reasoning_steps: list[dict]
    hypotheses_generated: int
    hypotheses_eliminated: int
    survived_disconfirmation: bool
    disconfirmation_result: dict | None
    historical_pattern_matches: list[dict]
    entity_state: dict | None
    status: ChainStatus
    created_at: str
    validate_at: str

    def to_dict(self) -> dict:
        return {
            "chain_id": self.chain_id,
            "trigger_signal_id": self.trigger_signal_id,
            "trigger_content": self.trigger_content,
            "center_entity": self.center_entity,
            "proposed_cause": self.proposed_cause,
            "proposed_effect": self.proposed_effect,
            "predicted_timeline_days": self.predicted_timeline_days,
            "confidence": self.confidence,
            "supporting_signal_ids": self.supporting_signal_ids,
            "contradicting_signal_ids": self.contradicting_signal_ids,
            "key_assumptions": self.key_assumptions,
            "reasoning_steps": self.reasoning_steps,
            "hypotheses_generated": self.hypotheses_generated,
            "hypotheses_eliminated": self.hypotheses_eliminated,
            "survived_disconfirmation": self.survived_disconfirmation,
            "disconfirmation_result": self.disconfirmation_result,
            "historical_pattern_matches": [m for m in self.historical_pattern_matches],
            "entity_state": self.entity_state,
            "status": self.status.value,
            "created_at": self.created_at,
            "validate_at": self.validate_at,
        }

    def to_summary(self) -> str:
        """Human-readable summary for dashboards and notifications."""
        return (
            f"Chain {self.chain_id} | Confidence: {self.confidence:.0%}\n"
            f"Entity: {self.center_entity}\n"
            f"Cause: {self.proposed_cause}\n"
            f"Effect: {self.proposed_effect}\n"
            f"Timeline: {self.predicted_timeline_days or 'unknown'} days\n"
            f"Hypotheses: {self.hypotheses_generated} generated, "
            f"{self.hypotheses_eliminated} eliminated\n"
            f"Disconfirmation: {'Survived' if self.survived_disconfirmation else 'Failed'}\n"
            f"Supporting signals: {len(self.supporting_signal_ids)}\n"
            f"Contradicting signals: {len(self.contradicting_signal_ids)}"
        )


# ============================================================
# GEMINI INTERFACE
# ============================================================

class GeminiInterface:
    """
    Wrapper around Gemini for causal chain reasoning.
    Uses google-genai for direct API calls.
    """

    def __init__(self):
        self.model_name = os.getenv("GEMINI_MODEL", "gemini-2.5-pro")
        self.temperature = float(os.getenv("GEMINI_TEMPERATURE", "0.3"))
        self.max_tokens = int(os.getenv("GEMINI_MAX_TOKENS", "8192"))
        self._client = None

    def _get_client(self):
        if self._client is None:
            import os
            from google import genai
            api_key = os.getenv("GEMINI_API_KEY")
            if api_key:
                self._client = genai.Client(api_key=api_key)
            else:
                self._client = genai.Client()
        return self._client

    async def generate(self, prompt: str, temperature: float | None = None) -> str:
        """Generate a response from Gemini."""
        import asyncio

        client = self._get_client()
        temp = temperature if temperature is not None else self.temperature

        try:
            loop = asyncio.get_event_loop()
            response = await loop.run_in_executor(
                None,
                lambda: client.models.generate_content(
                    model=self.model_name,
                    contents=prompt,
                    config={
                        "temperature": temp,
                        "max_output_tokens": self.max_tokens,
                    },
                ),
            )
            return response.text or ""
        except Exception as e:
            logger.error(
                "gemini.generate_error",
                error=str(e),
                prompt_length=len(prompt),
            )
            raise

# ============================================================
# PROMPT TEMPLATES
# ============================================================

HYPOTHESIS_GENERATION_PROMPT = """You are Veridian, an autonomous business intelligence system.
Your job is to generate hypotheses about what a cluster of business signals means.

CRITICAL CONSTRAINT:
Every hypothesis MUST be grounded in the retrieved evidence below.
You may NOT introduce facts, companies, events, or claims not present in the evidence.
If you reference something not in the evidence, your hypothesis is invalid.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
TRIGGER SIGNAL:
{trigger_signal}

ENTITY STATE:
{entity_state}

RELATED SIGNALS ({signal_count} found):
{evidence_signals}

HISTORICAL PATTERN MATCHES ({pattern_count} found):
{historical_patterns}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Generate exactly 3 hypotheses. They must be genuinely different explanations.

For EACH hypothesis, output in this EXACT format:

---HYPOTHESIS---
CENTER_ENTITY: [entity name]
PROPOSED_CAUSE: [one sentence describing the cause, citing signal IDs]
PROPOSED_EFFECT: [one sentence describing what will happen]
CAUSAL_MECHANISM: [2-3 sentences explaining WHY cause leads to effect]
SUPPORTING_SIGNALS: [comma-separated signal IDs from evidence]
DISCONFIRMATION_TEST: [what specific evidence would DISPROVE this]
INITIAL_CONFIDENCE: [0.1 to 0.8 — be conservative]
TIMELINE_DAYS: [estimated days until effect manifests, or UNKNOWN]
---END---

If evidence cannot support 3 hypotheses, generate fewer and add:
---INSUFFICIENT---
REASON: [why fewer than 3]
---END---
"""

HYPOTHESIS_TESTING_PROMPT = """You are scoring a specific hypothesis against retrieved evidence.
Use ONLY the evidence provided. Do not draw on training data.

HYPOTHESIS UNDER TEST:
Center Entity: {center_entity}
Proposed Cause: {proposed_cause}
Proposed Effect: {proposed_effect}
Causal Mechanism: {causal_mechanism}

SUPPORTING EVIDENCE RETRIEVED ({supporting_count} signals):
{supporting_evidence}

CONTRADICTING EVIDENCE RETRIEVED ({contradicting_count} signals):
{contradicting_evidence}

Score each dimension from 0.0 to 1.0:

EVIDENCE_STRENGTH: [how strongly does supporting evidence support the SPECIFIC causal claim?]
CONSISTENCY: [is the supporting evidence internally consistent?]
CONTRADICTION_SEVERITY: [how decisively does contradicting evidence undermine this?]
CAUSAL_SPECIFICITY: [is there a specific mechanism, or just correlation?]
ALTERNATIVE_EXPLANATION_RISK: [could same evidence support a completely different chain?]

Output in this EXACT format:
---SCORES---
EVIDENCE_STRENGTH: [0.0-1.0]
CONSISTENCY: [0.0-1.0]
CONTRADICTION_SEVERITY: [0.0-1.0]
CAUSAL_SPECIFICITY: [0.0-1.0]
ALTERNATIVE_EXPLANATION_RISK: [0.0-1.0]
OVERALL_SCORE: [weighted average]
VERDICT: [SURVIVED or ELIMINATED]
DECISIVE_REASON: [single most important reason for verdict]
---END---
"""

DISCONFIRMATION_PROMPT = """You have a hypothesis that survived initial testing.
Your job is to try to BREAK IT. Be adversarial.

WINNING HYPOTHESIS:
Center Entity: {center_entity}
Proposed Cause: {proposed_cause}
Proposed Effect: {proposed_effect}
Causal Mechanism: {causal_mechanism}
Current Confidence: {confidence}

CHALLENGE EVIDENCE ({challenge_count} signals found specifically to challenge this):
{challenge_evidence}

EXPECTED-BUT-ABSENT ANALYSIS:
If this hypothesis is correct, we would expect to find certain signals.
Signals we searched for but did NOT find:
{expected_but_absent}

Attack this hypothesis from 4 angles:

1. REVERSE CAUSATION: Could the effect be causing the cause?
2. CONFOUNDING VARIABLE: Is there a third factor explaining both?
3. ABSENT EVIDENCE: Do missing expected signals undermine this?
4. SCOPE PROBLEM: Is the hypothesis true but smaller than claimed?

Output in this EXACT format:
---DISCONFIRMATION---
REVERSE_CAUSATION_RISK: [LOW/MEDIUM/HIGH with one sentence explanation]
CONFOUNDING_VARIABLE_RISK: [LOW/MEDIUM/HIGH with one sentence explanation]
ABSENT_EVIDENCE_ASSESSMENT: [EXPLAINABLE/CONCERNING/DAMAGING with explanation]
SCOPE_ADJUSTMENT: [NONE/NARROWER/MUCH_NARROWER with explanation]
VERDICT: [STANDS or MODIFIED or REJECTED]
MODIFIED_HYPOTHESIS: [if MODIFIED, state the exact modification, else NONE]
KILLER_EVIDENCE: [if REJECTED, state the exact killer evidence, else NONE]
CONFIDENCE_ADJUSTMENT: [float between -0.3 and +0.1]
---END---
"""

CONFIDENCE_CALIBRATION_PROMPT = """You are calibrating the final confidence for a causal chain.

Apply these rules deterministically:

CHAIN SUMMARY:
{chain_summary}

EVIDENCE SCORES:
Evidence strength: {evidence_strength}
Contradiction severity: {contradiction_severity}
Causal specificity: {causal_specificity}
Disconfirmation verdict: {disconfirmation_verdict}
Disconfirmation confidence adjustment: {disconfirmation_adjustment}
Historical pattern matches: {pattern_match_count}
Historical accuracy of similar chains: {historical_accuracy}
Supporting signal count: {supporting_count}
Contradicting signal count: {contradicting_count}

CALIBRATION RULES (apply in order):
1. Base confidence = evidence_strength score
2. Subtract contradiction_severity * 0.3
3. If disconfirmation found concerns, apply confidence_adjustment
4. If disconfirmation verdict is REJECTED, cap at 0.15
5. If no historical patterns exist, reduce by 0.1
6. If historical accuracy for similar chains < 60%, reduce by 0.15
7. If supporting signals < 3, reduce by 0.1
8. If contradicting signals > supporting signals, reduce by 0.2
9. NEVER exceed 0.90
10. NEVER go below 0.10

Output in this EXACT format:
---CALIBRATION---
BASE: [step 1 result]
AFTER_CONTRADICTION: [step 2 result]
AFTER_DISCONFIRMATION: [step 3 result]
AFTER_HISTORY: [steps 5-6 result]
AFTER_SIGNAL_COUNT: [steps 7-8 result]
FINAL_CONFIDENCE: [after all caps applied]
KEY_ASSUMPTIONS: [3-5 bullet points, one per line starting with •]
---END---
"""


# ============================================================
# PARSERS
# ============================================================

def _parse_hypotheses(response_text: str) -> list[Hypothesis]:
    """Parse Gemini's hypothesis output into structured objects."""
    hypotheses = []
    blocks = response_text.split("---HYPOTHESIS---")

    for block in blocks[1:]:  # Skip text before first marker
        if "---END---" not in block:
            continue

        content = block.split("---END---")[0].strip()
        h = Hypothesis(
            hypothesis_id=f"H-{uuid.uuid4().hex[:6].upper()}",
            center_entity=_extract_field(content, "CENTER_ENTITY"),
            proposed_cause=_extract_field(content, "PROPOSED_CAUSE"),
            proposed_effect=_extract_field(content, "PROPOSED_EFFECT"),
            causal_mechanism=_extract_field(content, "CAUSAL_MECHANISM"),
            supporting_signal_ids=[
                s.strip() for s in _extract_field(content, "SUPPORTING_SIGNALS").split(",")
                if s.strip()
            ],
            disconfirmation_test=_extract_field(content, "DISCONFIRMATION_TEST"),
            initial_confidence=_extract_float(content, "INITIAL_CONFIDENCE", default=0.4),
            timeline_estimate_days=_extract_int(content, "TIMELINE_DAYS"),
        )

        # Validate: skip empty hypotheses
        if h.proposed_cause and h.proposed_effect:
            hypotheses.append(h)

    return hypotheses


def _parse_test_scores(response_text: str) -> dict[str, Any]:
    """Parse hypothesis test scores from Gemini response."""
    block = response_text
    if "---SCORES---" in block:
        block = block.split("---SCORES---")[1]
    if "---END---" in block:
        block = block.split("---END---")[0]

    return {
        "evidence_strength": _extract_float(block, "EVIDENCE_STRENGTH", 0.5),
        "consistency": _extract_float(block, "CONSISTENCY", 0.5),
        "contradiction_severity": _extract_float(block, "CONTRADICTION_SEVERITY", 0.3),
        "causal_specificity": _extract_float(block, "CAUSAL_SPECIFICITY", 0.5),
        "alternative_explanation_risk": _extract_float(block, "ALTERNATIVE_EXPLANATION_RISK", 0.5),
        "overall_score": _extract_float(block, "OVERALL_SCORE", 0.5),
        "verdict": _extract_field(block, "VERDICT").upper().strip(),
        "decisive_reason": _extract_field(block, "DECISIVE_REASON"),
    }


def _parse_disconfirmation(response_text: str) -> DisconfirmationResult:
    """Parse disconfirmation result from Gemini response."""
    block = response_text
    if "---DISCONFIRMATION---" in block:
        block = block.split("---DISCONFIRMATION---")[1]
    if "---END---" in block:
        block = block.split("---END---")[0]

    verdict_str = _extract_field(block, "VERDICT").upper().strip()
    if "REJECT" in verdict_str:
        verdict = DisconfirmationVerdict.REJECTED
    elif "MODIF" in verdict_str:
        verdict = DisconfirmationVerdict.MODIFIED
    else:
        verdict = DisconfirmationVerdict.STANDS

    modified_hyp = _extract_field(block, "MODIFIED_HYPOTHESIS")
    killer = _extract_field(block, "KILLER_EVIDENCE")

    return DisconfirmationResult(
        verdict=verdict,
        challenge_signals_found=0,  # Filled in by caller
        reverse_causation_risk=_extract_field(block, "REVERSE_CAUSATION_RISK"),
        confounding_variable_risk=_extract_field(block, "CONFOUNDING_VARIABLE_RISK"),
        absent_evidence_assessment=_extract_field(block, "ABSENT_EVIDENCE_ASSESSMENT"),
        scope_adjustment=_extract_field(block, "SCOPE_ADJUSTMENT"),
        modified_hypothesis=modified_hyp if modified_hyp.upper() != "NONE" else None,
        killer_evidence=killer if killer.upper() != "NONE" else None,
        confidence_adjustment=_extract_float(block, "CONFIDENCE_ADJUSTMENT", 0.0),
    )


def _parse_calibration(response_text: str) -> tuple[float, list[str]]:
    """Parse calibration result — returns (confidence, key_assumptions)."""
    block = response_text
    if "---CALIBRATION---" in block:
        block = block.split("---CALIBRATION---")[1]
    if "---END---" in block:
        block = block.split("---END---")[0]

    confidence = _extract_float(block, "FINAL_CONFIDENCE", 0.5)
    confidence = max(0.10, min(0.90, confidence))

    assumptions_raw = _extract_field(block, "KEY_ASSUMPTIONS")
    assumptions = [
        line.strip().lstrip("•").strip()
        for line in assumptions_raw.split("\n")
        if line.strip() and line.strip() != "•"
    ]

    return confidence, assumptions


def _extract_field(text: str, field_name: str) -> str:
    """Extract a field value from structured text output."""
    for line in text.split("\n"):
        if line.strip().upper().startswith(field_name.upper() + ":"):
            return line.split(":", 1)[1].strip()
    return ""


def _extract_float(text: str, field_name: str, default: float = 0.0) -> float:
    """Extract a float field value."""
    raw = _extract_field(text, field_name)
    try:
        return float(raw)
    except (ValueError, TypeError):
        return default


def _extract_int(text: str, field_name: str) -> int | None:
    """Extract an integer field value."""
    raw = _extract_field(text, field_name)
    if raw.upper() in ("UNKNOWN", "NONE", "N/A", ""):
        return None
    try:
        return int(float(raw))
    except (ValueError, TypeError):
        return None


def _format_signals_for_prompt(signals: list[SignalResult]) -> str:
    """Format signal list for inclusion in Gemini prompt."""
    if not signals:
        return "No signals found."

    lines = []
    for i, sig in enumerate(signals, 1):
        lines.append(
            f"[{i}] ID: {sig.signal_id}\n"
            f"    Source: {sig.source} | Type: {sig.signal_type}\n"
            f"    Entities: {', '.join(sig.entity_hints) or 'none'}\n"
            f"    Relevance: {sig.relevance_score:.2f} | "
            f"Impact: {sig.impact_score:.2f}\n"
            f"    Timestamp: {sig.timestamp}\n"
            f"    Content: {sig.raw_content[:250]}\n"
        )
    return "\n".join(lines)


# ============================================================
# THE ENGINE
# ============================================================

class CausalChainEngine:
    """
    The 7-step causal chain protocol.

    Usage:
        engine = CausalChainEngine()
        chain = await engine.build_chain(trigger_signal_id, trigger_content)
        if chain:
            print(chain.to_summary())
    """

    def __init__(self):
        self.mcp = VeridianMCPClient()
        self.gemini = GeminiInterface()

    async def build_chain(
        self,
        trigger_signal_id: str,
        trigger_content: str,
        trigger_entities: list[str] | None = None,
    ) -> CausalChain | None:
        """
        Execute the full 7-step protocol on a trigger signal.

        Returns a CausalChain if the signal is anomalous and
        a hypothesis survives all testing, or None if the signal
        is noise or no hypothesis survives.
        """
        chain_id = f"VRD-CHN-{uuid.uuid4().hex[:8].upper()}"
        audit_trail: list[AuditStep] = []
        step_num = 0

        logger.info(
            "chain_engine.build_start",
            chain_id=chain_id,
            trigger_signal_id=trigger_signal_id,
            trigger_entities=trigger_entities,
        )

        # ══════════════════════════════════════════════
        # STEP 1: ANOMALY CONFIRMATION
        # Is this signal statistically anomalous?
        # ══════════════════════════════════════════════
        step_num += 1
        logger.info("chain_engine.step", step=1, name="anomaly_confirmation")

        primary_entity = (trigger_entities[0] if trigger_entities else None)
        anomaly_result = None

        if primary_entity:
            try:
                anomaly_result = await self.mcp.compute_entity_anomaly(
                    entity_name=primary_entity,
                    metric="impact_score",
                    lookback_days=90,
                    current_window_days=7,
                )
            except Exception as e:
                logger.warning("chain_engine.anomaly_check_failed", error=str(e))

        # For hackathon demo: even if anomaly check fails or returns
        # non-anomalous, proceed with chain building if we have entities.
        # In production, we'd stop here for non-anomalous signals.
        is_anomalous = (
            anomaly_result is not None and anomaly_result.is_anomalous
        ) or (primary_entity is not None)

        audit_trail.append(AuditStep(
            step_number=step_num,
            step_name="anomaly_confirmation",
            tool_used="mcp:compute_entity_anomaly",
            input_summary=f"Entity: {primary_entity or 'none'}, Metric: impact_score",
            output_summary=(
                anomaly_result.format_for_prompt() if anomaly_result
                else "No entity to check — proceeding based on signal content"
            ),
            reasoning=(
                f"Z-score: {anomaly_result.z_score:.2f}, "
                f"Anomalous: {anomaly_result.is_anomalous}" if anomaly_result
                else "Proceeding without anomaly score — entity-based trigger"
            ),
        ).to_dict())

        if not is_anomalous:
            logger.info("chain_engine.not_anomalous", chain_id=chain_id)
            return None

        # ══════════════════════════════════════════════
        # STEP 2: EVIDENCE RETRIEVAL
        # What related signals exist in memory?
        # ══════════════════════════════════════════════
        step_num += 1
        logger.info("chain_engine.step", step=2, name="evidence_retrieval")

        # 2a: Find semantically related signals
        related_signals = await self.mcp.find_related_signals(
            query=trigger_content[:300],
            time_range_days=90,
            min_score=0.5,
            limit=20,
            exclude_signal_ids=[trigger_signal_id],
        )

        # 2b: Get entity state (if entity exists)
        entity_state = None
        if primary_entity:
            try:
                entity_state = await self.mcp.get_entity_state(
                    entity_name=primary_entity,
                    dimensions=["news", "community", "financial", "hiring"],
                    lookback_days=90,
                )
            except Exception as e:
                logger.warning("chain_engine.entity_state_failed", error=str(e))

        # 2c: Find historical pattern matches
        signal_ids_for_pattern = [trigger_signal_id]
        if related_signals.signals:
            signal_ids_for_pattern.extend(
                [s.signal_id for s in related_signals.signals[:4]]
            )
        historical_patterns = await self.mcp.find_historical_pattern(
            current_signal_ids=signal_ids_for_pattern,
            top_k=5,
        )

        audit_trail.append(AuditStep(
            step_number=step_num,
            step_name="evidence_retrieval",
            tool_used="mcp:find_related_signals + get_entity_state + find_historical_pattern",
            input_summary=f"Trigger: {trigger_content[:100]}...",
            output_summary=(
                f"Related signals: {related_signals.total_found}, "
                f"Entity state: {'retrieved' if entity_state else 'unavailable'}, "
                f"Historical patterns: {len(historical_patterns.matches)}"
            ),
            reasoning=(
                f"Found {related_signals.total_found} semantically related signals. "
                f"{'Strong precedent exists.' if historical_patterns.has_strong_precedent else 'No strong historical precedent.'}"
            ),
        ).to_dict())

        # ══════════════════════════════════════════════
        # STEP 3: HYPOTHESIS GENERATION
        # What could explain this cluster? (Gemini)
        # ══════════════════════════════════════════════
        step_num += 1
        logger.info("chain_engine.step", step=3, name="hypothesis_generation")

        hypothesis_prompt = HYPOTHESIS_GENERATION_PROMPT.format(
            trigger_signal=trigger_content[:500],
            entity_state=(
                entity_state.format_for_prompt() if entity_state
                else "No entity state available."
            ),
            signal_count=len(related_signals.signals),
            evidence_signals=_format_signals_for_prompt(related_signals.signals[:15]),
            pattern_count=len(historical_patterns.matches),
            historical_patterns=(
                historical_patterns.format_for_prompt() if historical_patterns.matches
                else "No historical patterns found."
            ),
        )

        hypothesis_response = await self.gemini.generate(
            hypothesis_prompt,
            temperature=0.3,
        )

        hypotheses = _parse_hypotheses(hypothesis_response)

        if not hypotheses:
            logger.warning(
                "chain_engine.no_hypotheses_generated",
                chain_id=chain_id,
            )
            audit_trail.append(AuditStep(
                step_number=step_num,
                step_name="hypothesis_generation",
                tool_used="gemini",
                input_summary=f"{len(related_signals.signals)} signals + entity state provided",
                output_summary="No valid hypotheses generated",
                reasoning="Gemini could not generate grounded hypotheses from evidence",
            ).to_dict())
            return None

        audit_trail.append(AuditStep(
            step_number=step_num,
            step_name="hypothesis_generation",
            tool_used="gemini",
            input_summary=f"{len(related_signals.signals)} signals + entity state provided",
            output_summary=f"{len(hypotheses)} hypotheses generated",
            reasoning="; ".join(
                f"H{i+1}: {h.proposed_cause[:80]}"
                for i, h in enumerate(hypotheses)
            ),
        ).to_dict())

        # ══════════════════════════════════════════════
        # STEP 4: HYPOTHESIS TESTING
        # Does evidence support or contradict?
        # ══════════════════════════════════════════════
        step_num += 1
        logger.info("chain_engine.step", step=4, name="hypothesis_testing")

        test_results: list[HypothesisTestResult] = []

        for h in hypotheses:
            # 4a: Find supporting evidence
            supporting = await self.mcp.find_related_signals(
                query=f"{h.proposed_cause} {h.proposed_effect}",
                time_range_days=90,
                min_score=0.5,
                limit=10,
                exclude_signal_ids=[trigger_signal_id],
            )

            # 4b: Find contradicting evidence
            contradicting = await self.mcp.find_related_signals(
                query=h.disconfirmation_test,
                time_range_days=90,
                min_score=0.4,
                limit=10,
                exclude_signal_ids=[trigger_signal_id],
            )

            # 4c: Gemini scores the hypothesis
            test_prompt = HYPOTHESIS_TESTING_PROMPT.format(
                center_entity=h.center_entity,
                proposed_cause=h.proposed_cause,
                proposed_effect=h.proposed_effect,
                causal_mechanism=h.causal_mechanism,
                supporting_count=len(supporting.signals),
                supporting_evidence=_format_signals_for_prompt(supporting.signals[:8]),
                contradicting_count=len(contradicting.signals),
                contradicting_evidence=_format_signals_for_prompt(contradicting.signals[:8]),
            )

            test_response = await self.gemini.generate(test_prompt, temperature=0.2)
            scores = _parse_test_scores(test_response)

            overall = scores.get("overall_score", 0.5)
            contradiction = scores.get("contradiction_severity", 0.3)
            verdict_str = scores.get("verdict", "ELIMINATED")

            survived = overall > 0.35

            test_result = HypothesisTestResult(
                hypothesis=h,
                evidence_strength=scores.get("evidence_strength", 0.5),
                consistency=scores.get("consistency", 0.5),
                contradiction_severity=contradiction,
                causal_specificity=scores.get("causal_specificity", 0.5),
                alternative_explanation_risk=scores.get("alternative_explanation_risk", 0.5),
                overall_score=overall,
                supporting_signals_found=len(supporting.signals),
                contradicting_signals_found=len(contradicting.signals),
                verdict=HypothesisVerdict.SURVIVED if survived else HypothesisVerdict.ELIMINATED,
                decisive_reason=scores.get("decisive_reason", "No reason provided"),
            )
            test_results.append(test_result)

            logger.info(
                "chain_engine.hypothesis_tested",
                hypothesis_id=h.hypothesis_id,
                overall_score=overall,
                verdict="SURVIVED" if survived else "ELIMINATED",
            )

        surviving = [t for t in test_results if t.verdict == HypothesisVerdict.SURVIVED]
        eliminated = [t for t in test_results if t.verdict == HypothesisVerdict.ELIMINATED]

        audit_trail.append(AuditStep(
            step_number=step_num,
            step_name="hypothesis_testing",
            tool_used="mcp:find_related_signals + gemini",
            input_summary=f"Tested {len(hypotheses)} hypotheses",
            output_summary=f"{len(surviving)} survived, {len(eliminated)} eliminated",
            reasoning="; ".join(
                f"{t.hypothesis.hypothesis_id}: {t.verdict.value} "
                f"(score={t.overall_score:.2f}, reason: {t.decisive_reason[:60]})"
                for t in test_results
            ),
        ).to_dict())

        if not surviving:
            logger.info(
                "chain_engine.all_hypotheses_eliminated",
                chain_id=chain_id,
            )
            return None

        # ══════════════════════════════════════════════
        # STEP 5: WINNER SELECTION
        # Which hypothesis survives testing?
        # ══════════════════════════════════════════════
        step_num += 1
        logger.info("chain_engine.step", step=5, name="winner_selection")

        winner = max(surviving, key=lambda t: t.overall_score)

        audit_trail.append(AuditStep(
            step_number=step_num,
            step_name="winner_selection",
            tool_used="deterministic_ranking",
            input_summary=f"{len(surviving)} surviving hypotheses",
            output_summary=f"Winner: {winner.hypothesis.hypothesis_id} (score={winner.overall_score:.2f})",
            reasoning=(
                f"Selected hypothesis with highest overall score. "
                f"Cause: {winner.hypothesis.proposed_cause[:100]}"
            ),
        ).to_dict())

        # ══════════════════════════════════════════════
        # STEP 6: ACTIVE DISCONFIRMATION
        # Can we BREAK the winning hypothesis?
        # ══════════════════════════════════════════════
        step_num += 1
        logger.info("chain_engine.step", step=6, name="active_disconfirmation")

        # 6a: Search for challenge evidence
        challenge_signals = await self.mcp.find_related_signals(
            query=winner.hypothesis.disconfirmation_test,
            time_range_days=180,
            min_score=0.4,
            limit=15,
        )

        # 6b: Search for expected-but-absent evidence
        expected_signals = await self.mcp.find_related_signals(
            query=f"evidence of {winner.hypothesis.proposed_effect}",
            time_range_days=90,
            min_score=0.6,
            limit=5,
        )
        expected_present = len(expected_signals.signals) > 0

        # 6c: Gemini tries to break the hypothesis
        disconfirmation_prompt = DISCONFIRMATION_PROMPT.format(
            center_entity=winner.hypothesis.center_entity,
            proposed_cause=winner.hypothesis.proposed_cause,
            proposed_effect=winner.hypothesis.proposed_effect,
            causal_mechanism=winner.hypothesis.causal_mechanism,
            confidence=winner.overall_score,
            challenge_count=len(challenge_signals.signals),
            challenge_evidence=_format_signals_for_prompt(challenge_signals.signals[:10]),
            expected_but_absent=(
                "Expected outcome signals FOUND — consistent with hypothesis."
                if expected_present
                else "Expected outcome signals NOT FOUND — hypothesis predicts "
                     "signals that do not yet exist in our data."
            ),
        )

        disconfirmation_response = await self.gemini.generate(
            disconfirmation_prompt,
            temperature=0.2,
        )
        disconfirmation = _parse_disconfirmation(disconfirmation_response)
        disconfirmation.challenge_signals_found = len(challenge_signals.signals)

        survived_disconfirmation = (
            disconfirmation.verdict != DisconfirmationVerdict.REJECTED
        )

        # If modified, update the hypothesis
        if disconfirmation.verdict == DisconfirmationVerdict.MODIFIED:
            if disconfirmation.modified_hypothesis:
                winner.hypothesis.proposed_effect = disconfirmation.modified_hypothesis

        audit_trail.append(AuditStep(
            step_number=step_num,
            step_name="active_disconfirmation",
            tool_used="mcp:find_related_signals + gemini",
            input_summary=(
                f"Challenge signals: {len(challenge_signals.signals)}, "
                f"Expected evidence: {'present' if expected_present else 'absent'}"
            ),
            output_summary=(
                f"Verdict: {disconfirmation.verdict.value}, "
                f"Confidence adj: {disconfirmation.confidence_adjustment:+.2f}"
            ),
            reasoning=(
                f"Reverse causation: {disconfirmation.reverse_causation_risk}, "
                f"Confounding: {disconfirmation.confounding_variable_risk}, "
                f"Absent evidence: {disconfirmation.absent_evidence_assessment}"
            ),
        ).to_dict())

        if not survived_disconfirmation:
            logger.info(
                "chain_engine.disconfirmation_rejected",
                chain_id=chain_id,
                killer_evidence=disconfirmation.killer_evidence,
            )
            # Still return chain for audit purposes, but mark as rejected
            pass

        # ══════════════════════════════════════════════
        # STEP 7: CONFIDENCE CALIBRATION
        # What confidence does the evidence warrant?
        # ══════════════════════════════════════════════
        step_num += 1
        logger.info("chain_engine.step", step=7, name="confidence_calibration")

        # Get historical accuracy for similar chains
        historical_accuracy = "unknown"
        if historical_patterns.matches:
            accuracies = [m.historical_accuracy for m in historical_patterns.matches if m.historical_accuracy > 0]
            if accuracies:
                historical_accuracy = f"{sum(accuracies)/len(accuracies):.0%}"

        calibration_prompt = CONFIDENCE_CALIBRATION_PROMPT.format(
            chain_summary=(
                f"Entity: {winner.hypothesis.center_entity}. "
                f"Cause: {winner.hypothesis.proposed_cause}. "
                f"Effect: {winner.hypothesis.proposed_effect}."
            ),
            evidence_strength=winner.evidence_strength,
            contradiction_severity=winner.contradiction_severity,
            causal_specificity=winner.causal_specificity,
            disconfirmation_verdict=disconfirmation.verdict.value,
            disconfirmation_adjustment=disconfirmation.confidence_adjustment,
            pattern_match_count=len(historical_patterns.matches),
            historical_accuracy=historical_accuracy,
            supporting_count=winner.supporting_signals_found,
            contradicting_count=winner.contradicting_signals_found,
        )

        calibration_response = await self.gemini.generate(
            calibration_prompt,
            temperature=0.1,
        )
        final_confidence, key_assumptions = _parse_calibration(calibration_response)

        # Deterministic override: if disconfirmation rejected, cap confidence
        if not survived_disconfirmation:
            final_confidence = min(final_confidence, 0.15)

        audit_trail.append(AuditStep(
            step_number=step_num,
            step_name="confidence_calibration",
            tool_used="gemini + deterministic_rules",
            input_summary=(
                f"Evidence: {winner.evidence_strength:.2f}, "
                f"Contradiction: {winner.contradiction_severity:.2f}, "
                f"Disconfirmation: {disconfirmation.verdict.value}"
            ),
            output_summary=f"Final confidence: {final_confidence:.2f}",
            reasoning=f"Applied 10-step calibration protocol. Key assumptions: {'; '.join(key_assumptions[:3])}",
        ).to_dict())

        # ══════════════════════════════════════════════
        # BUILD THE CHAIN
        # ══════════════════════════════════════════════
        now = datetime.now(timezone.utc)
        validate_days = winner.hypothesis.timeline_estimate_days or 30

        chain = CausalChain(
            chain_id=chain_id,
            trigger_signal_id=trigger_signal_id,
            trigger_content=trigger_content[:500],
            center_entity=winner.hypothesis.center_entity,
            proposed_cause=winner.hypothesis.proposed_cause,
            proposed_effect=winner.hypothesis.proposed_effect,
            predicted_timeline_days=winner.hypothesis.timeline_estimate_days,
            confidence=round(final_confidence, 4),
            supporting_signal_ids=list(set(
                winner.hypothesis.supporting_signal_ids
                + [s.signal_id for s in related_signals.signals[:5]]
            )),
            contradicting_signal_ids=[
                s.signal_id for s in challenge_signals.signals[:5]
            ],
            key_assumptions=key_assumptions,
            reasoning_steps=audit_trail,
            hypotheses_generated=len(hypotheses),
            hypotheses_eliminated=len(eliminated),
            survived_disconfirmation=survived_disconfirmation,
            disconfirmation_result=disconfirmation.to_dict(),
            historical_pattern_matches=[
                m.model_dump() for m in historical_patterns.matches
            ],
            entity_state=entity_state.model_dump() if entity_state else None,
            status=(
                ChainStatus.ACTIVE if survived_disconfirmation
                else ChainStatus.REJECTED
            ),
            created_at=now.isoformat(),
            validate_at=(now + timedelta(days=validate_days)).isoformat(),
        )

        # ══════════════════════════════════════════════
        # PERSIST TO ELASTICSEARCH
        # ══════════════════════════════════════════════
        try:
            from backend.es.client import get_client
            es = get_client()
            await es.index(
                index="veridian_causal_chains",
                id=chain_id,
                document=chain.to_dict(),
            )
            logger.info(
                "chain_engine.chain_stored",
                chain_id=chain_id,
                confidence=final_confidence,
            )
        except Exception as e:
            logger.error(
                "chain_engine.chain_store_error",
                chain_id=chain_id,
                error=str(e),
            )

        logger.info(
            "chain_engine.build_complete",
            chain_id=chain_id,
            center_entity=chain.center_entity,
            confidence=chain.confidence,
            hypotheses_generated=chain.hypotheses_generated,
            hypotheses_eliminated=chain.hypotheses_eliminated,
            survived_disconfirmation=chain.survived_disconfirmation,
        )

        return chain